name:       'Fogies Base'
baseurl:    ''

brandimage: ''
brandtext:  'Fogies'

exclude:
  # Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
